import { prisma } from "./mockDb";
import { getDashboardData } from "./analytics/dashboard";
import { getInventorySuggestions } from "./inventory/suggestions";
import { getSummaryData, csvFromSummary } from "./reports/report";
import { answerAssistantQuery } from "./assistant/assistant";
import { parseUpiSmsText } from "./upi/parser";

const isBrowser = typeof window !== "undefined";

function parseUrlParams(urlStr: string): URLSearchParams {
  const qIdx = urlStr.indexOf("?");
  return qIdx !== -1 ? new URLSearchParams(urlStr.substring(qIdx)) : new URLSearchParams();
}

function extractIdFromUrl(urlStr: string, prefix: string): string | null {
  const parts = urlStr.split("?")[0].split("/");
  const last = parts[parts.length - 1];
  const prev = parts[parts.length - 2];
  if (prev === prefix) return last;
  return null;
}

// Make a client-side mock PDF using actual PDF stream syntax so it opens correctly in browser
function generateSimplePdf(summary: any): Blob {
  const lines = [
    summary.label,
    `From: ${summary.start.toISOString().slice(0, 10)} | To: ${summary.end.toISOString().slice(0, 10)}`,
    "",
    `Income (credits): INR ${summary.income.toFixed(2)}`,
    `Refunds: INR ${summary.refunds.toFixed(2)}`,
    `Revenue (income - refunds): INR ${summary.revenue.toFixed(2)}`,
    `Expenses: INR ${summary.expenseTotal.toFixed(2)}`,
    `Estimated Profit: INR ${summary.profit.toFixed(2)}`,
    "",
    "Generated by Small Business Smart Assistant (UPI++).",
  ];

  // Escapes parentheses for PDF syntax
  const escapePdfText = (t: string) => t.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  const streamContent =
    "BT\n/F1 12 Tf\n50 750 Td\n18 TL\n" +
    lines.map((l) => `(${escapePdfText(l)}) Tj T*`).join("\n") +
    "\nET";

  const pdfBody = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /Contents 4 0 R >>
endobj
4 0 obj
<< /Length ${streamContent.length} >>
stream
${streamContent}
endstream
endobj
xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000282 00000 n
trailer
<< /Size 5 /Root 1 0 R >>
startxref
${282 + streamContent.length + 100}
%%EOF`;

  return new Blob([pdfBody], { type: "application/pdf" });
}

async function handleMockApi(urlStr: string, init?: RequestInit): Promise<Response> {
  const method = init?.method?.toUpperCase() ?? "GET";
  const params = parseUrlParams(urlStr);
  const cleanUrl = urlStr.split("?")[0];

  const headers = new Headers({ "Content-Type": "application/json" });

  try {
    // 1. Auth Me
    if (cleanUrl === "/api/auth/me" && method === "GET") {
      const user = await prisma.user.findFirst();
      return new Response(JSON.stringify({ user }), { status: 200, headers });
    }

    // 2. Auth Logout
    if (cleanUrl === "/api/auth/logout" && method === "POST") {
      return new Response(JSON.stringify({ success: true }), { status: 200, headers });
    }

    // 3. Settings Language
    if (cleanUrl === "/api/settings/language" && method === "POST") {
      const body = JSON.parse(init?.body as string);
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "No user found" }), { status: 404, headers });

      const updated = await prisma.user.update({
        where: { id: user.id },
        data: { language: body.language },
      });
      return new Response(JSON.stringify({ language: updated.language }), { status: 200, headers });
    }

    // 4. Dashboard Analytics
    if (cleanUrl === "/api/analytics/dashboard" && method === "GET") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });
      const data = await getDashboardData(user.id);
      return new Response(JSON.stringify(data), { status: 200, headers });
    }

    // 5. Alerts
    if (cleanUrl === "/api/alerts" && method === "GET") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      const dashboard = await getDashboardData(user.id);
      const inv = await getInventorySuggestions(user.id);

      const lowStock = inv.filter((s) => s.isLowStock);
      const fast = inv.filter((s) => s.movement === "fast");

      const alerts: Array<{ type: string; message: string }> = [];
      if (lowStock.length > 0) {
        alerts.push({
          type: "low_stock",
          message: `Low stock: ${lowStock
            .slice(0, 3)
            .map((s) => `${s.productName} (stock ${s.stockQuantity})`)
            .join(", ")}.`,
        });
      } else {
        alerts.push({ type: "low_stock", message: "Inventory looks healthy right now." });
      }

      alerts.push({ type: "unusual_sales_dip", message: dashboard.insights.salesDip });
      alerts.push({ type: "peak_hour", message: `Peak hour: ${dashboard.peakSalesHours.rangeLabel}.` });

      if (fast.length > 0) {
        alerts.push({
          type: "top_selling_restock",
          message: `Top-selling right now: ${fast[0].productName}. Reorder before the peak window.`,
        });
      }

      return new Response(JSON.stringify({ alerts }), { status: 200, headers });
    }

    // 6. Expenses List & Create
    if (cleanUrl === "/api/expenses") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      if (method === "GET") {
        const from = params.get("from");
        const to = params.get("to");
        const category = params.get("category");
        const limit = Number(params.get("limit") || "80");

        const where: any = { userId: user.id };
        if (from || to) {
          where.expenseTime = {};
          if (from) where.expenseTime.gte = new Date(from + "T00:00:00");
          if (to) where.expenseTime.lte = new Date(to + "T23:59:59");
        }
        if (category) where.category = category;

        const rows = await prisma.expense.findMany({
          where,
          orderBy: { expenseTime: "desc" },
          take: Math.max(1, Math.min(limit, 200)),
        });

        return new Response(
          JSON.stringify({
            expenses: rows.map((r) => ({ ...r, amount: Number(r.amount) })),
          }),
          { status: 200, headers }
        );
      }

      if (method === "POST") {
        const body = JSON.parse(init?.body as string);
        const expenseTime = body.expenseTime ? new Date(body.expenseTime) : new Date();

        const created = await prisma.expense.create({
          data: {
            userId: user.id,
            category: body.category,
            amount: body.amount,
            note: body.note ?? null,
            expenseTime: expenseTime.toISOString(),
          },
        });

        return new Response(JSON.stringify({ expense: { ...created, amount: Number(created.amount) } }), {
          status: 200,
          headers,
        });
      }
    }

    // 7. Inventory Items List, Create & Suggestions
    if (cleanUrl === "/api/inventory-items") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      if (method === "GET") {
        const rows = await prisma.inventoryItem.findMany({
          where: { userId: user.id },
          orderBy: { stockQuantity: "asc" },
        });
        return new Response(
          JSON.stringify({
            items: rows.map((r) => ({
              ...r,
              costPrice: Number(r.costPrice),
              sellingPrice: Number(r.sellingPrice),
            })),
          }),
          { status: 200, headers }
        );
      }

      if (method === "POST") {
        const body = JSON.parse(init?.body as string);
        const created = await prisma.inventoryItem.create({
          data: {
            userId: user.id,
            productName: body.productName,
            category: body.category,
            stockQuantity: body.stockQuantity,
            costPrice: body.costPrice,
            sellingPrice: body.sellingPrice,
            reorderLevel: body.reorderLevel,
          },
        });
        return new Response(
          JSON.stringify({
            item: {
              ...created,
              costPrice: Number(created.costPrice),
              sellingPrice: Number(created.sellingPrice),
            },
          }),
          { status: 200, headers }
        );
      }
    }

    if (cleanUrl === "/api/inventory-items/suggestions" && method === "GET") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });
      const suggestions = await getInventorySuggestions(user.id);
      return new Response(JSON.stringify(suggestions), { status: 200, headers });
    }

    // Inventory Item CRUD
    const itemId = extractIdFromUrl(urlStr, "inventory-items");
    if (itemId && cleanUrl.includes("/api/inventory-items/")) {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      if (method === "PATCH") {
        const body = JSON.parse(init?.body as string);
        const existing = await prisma.inventoryItem.findFirst({ where: { id: itemId, userId: user.id } });
        if (!existing) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers });

        const updated = await prisma.inventoryItem.update({
          where: { id: itemId },
          data: body,
        });

        return new Response(
          JSON.stringify({
            item: {
              ...updated,
              costPrice: Number(updated.costPrice),
              sellingPrice: Number(updated.sellingPrice),
            },
          }),
          { status: 200, headers }
        );
      }

      if (method === "DELETE") {
        const existing = await prisma.inventoryItem.findFirst({ where: { id: itemId, userId: user.id } });
        if (!existing) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers });

        await prisma.inventoryItem.delete({ where: { id: itemId } });
        return new Response(JSON.stringify({ ok: true }), { status: 200, headers });
      }
    }

    // 8. Transactions List, Create & Parse
    if (cleanUrl === "/api/transactions") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      if (method === "GET") {
        const from = params.get("from");
        const to = params.get("to");
        const category = params.get("category");
        const type = params.get("type");
        const minAmount = params.get("minAmount");
        const maxAmount = params.get("maxAmount");
        const q = params.get("q");
        const limit = Number(params.get("limit") || "50");

        const where: any = { userId: user.id };
        if (from || to) {
          where.transactionTime = {};
          if (from) where.transactionTime.gte = new Date(from + "T00:00:00");
          if (to) where.transactionTime.lte = new Date(to + "T23:59:59");
        }
        if (category) where.category = category;
        if (type) where.transactionType = type;
        if (minAmount || maxAmount) {
          where.amount = {};
          if (minAmount) where.amount.gte = Number(minAmount);
          if (maxAmount) where.amount.lte = Number(maxAmount);
        }
        if (q) {
          const qq = q.trim();
          where.OR = [
            { messageText: { contains: qq } },
            { customerName: { contains: qq } },
            { sourceApp: { contains: qq } },
          ];
        }

        const rows = await prisma.transaction.findMany({
          where,
          orderBy: { transactionTime: "desc" },
          take: Math.max(1, Math.min(limit, 200)),
        });

        return new Response(
          JSON.stringify({
            transactions: rows.map((r) => ({ ...r, amount: Number(r.amount) })),
          }),
          { status: 200, headers }
        );
      }

      if (method === "POST") {
        const body = JSON.parse(init?.body as string);
        const transactionTime = body.transactionTime ? new Date(body.transactionTime) : new Date();

        const created = await prisma.transaction.create({
          data: {
            userId: user.id,
            messageText: body.messageText ?? null,
            amount: body.amount,
            transactionType: body.transactionType,
            category: body.category,
            customerName: body.customerName ?? null,
            sourceApp: body.sourceApp ?? null,
            transactionTime: transactionTime.toISOString(),
            inventoryItemId: body.inventoryItemId ?? null,
            quantity: body.quantity ?? null,
          },
        });

        return new Response(JSON.stringify({ transaction: { ...created, amount: Number(created.amount) } }), {
          status: 200,
          headers,
        });
      }
    }

    if (cleanUrl === "/api/transactions/parse" && method === "POST") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      const body = JSON.parse(init?.body as string);
      const parsed = parseUpiSmsText(body.messagesText);

      if (parsed.length > 0) {
        await prisma.transaction.createMany({
          data: parsed.map((p) => ({
            userId: user.id,
            messageText: p.messageText,
            amount: p.amount,
            transactionType: p.transactionType,
            category: p.category,
            customerName: p.customerName,
            sourceApp: p.sourceApp,
            transactionTime: p.transactionTime ? p.transactionTime.toISOString() : new Date().toISOString(),
            inventoryItemId: null,
            quantity: null,
          })),
        });
      }

      return new Response(JSON.stringify({ ok: true, parsed, saved: parsed.length }), { status: 200, headers });
    }

    // Transaction CRUD
    const txId = extractIdFromUrl(urlStr, "transactions");
    if (txId && cleanUrl.includes("/api/transactions/")) {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      if (method === "PATCH") {
        const body = JSON.parse(init?.body as string);
        const existing = await prisma.transaction.findFirst({ where: { id: txId, userId: user.id } });
        if (!existing) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers });

        const data: any = { ...body };
        if (body.transactionTime) {
          data.transactionTime = new Date(body.transactionTime).toISOString();
        }

        const updated = await prisma.transaction.update({
          where: { id: txId },
          data,
        });

        return new Response(JSON.stringify({ transaction: { ...updated, amount: Number(updated.amount) } }), {
          status: 200,
          headers,
        });
      }

      if (method === "DELETE") {
        const existing = await prisma.transaction.findFirst({ where: { id: txId, userId: user.id } });
        if (!existing) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers });

        await prisma.transaction.delete({ where: { id: txId } });
        return new Response(JSON.stringify({ ok: true }), { status: 200, headers });
      }
    }

    // 9. Reports Summary
    if (cleanUrl === "/api/reports/summary" && method === "GET") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      const period = params.get("period") as "daily" | "weekly" | "monthly";
      const date = params.get("date") || undefined;
      const format = (params.get("format") || "pdf").toLowerCase();

      const summary = await getSummaryData({ userId: user.id, period, date });

      if (format === "csv") {
        const csv = csvFromSummary(summary);
        return new Response(csv, {
          status: 200,
          headers: new Headers({
            "Content-Type": "text/csv; charset=utf-8",
            "Content-Disposition": `attachment; filename="upi++_${period}_${date ?? "summary"}.csv"`,
          }),
        });
      }

      // Generate a mock PDF in the browser
      const pdfBlob = generateSimplePdf(summary);
      return new Response(pdfBlob, {
        status: 200,
        headers: new Headers({
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="upi++_${period}_${date ?? "summary"}.pdf"`,
        }),
      });
    }

    // 10. AI Assistant Query
    if (cleanUrl === "/api/assistant/ask" && method === "POST") {
      const user = await prisma.user.findFirst();
      if (!user) return new Response(JSON.stringify({ error: "Unauthenticated" }), { status: 401, headers });

      const body = JSON.parse(init?.body as string);
      const answer = await answerAssistantQuery({
        userId: user.id,
        question: body.question,
        language: (body.language ?? user.language) as any,
      });

      return new Response(JSON.stringify({ response: answer }), { status: 200, headers });
    }

    // Unmatched API
    return new Response(JSON.stringify({ error: "Mock endpoint not found" }), { status: 404, headers });
  } catch (err: any) {
    console.error("Mock API Error:", err);
    return new Response(JSON.stringify({ error: err.message ?? "Internal Server Error" }), {
      status: 500,
      headers,
    });
  }
}

// Intercept window.fetch if inside browser
export function setupMockApi() {
  if (!isBrowser) return;

  const originalFetch = window.fetch;
  window.fetch = async function (input: RequestInfo | URL, init?: RequestInit) {
    const urlStr =
      typeof input === "string"
        ? input
        : input instanceof URL
          ? input.toString()
          : (input as Request).url;

    if (urlStr.startsWith("/api/") || urlStr.includes("/api/")) {
      // Find the path starting from /api/
      const apiIdx = urlStr.indexOf("/api/");
      const relativeApiUrl = urlStr.substring(apiIdx);
      return handleMockApi(relativeApiUrl, init);
    }

    return originalFetch(input, init);
  };
}
