import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";

function toISODate(d: Date) {
  return d.toISOString().slice(0, 10);
}

function startOfDay(d: Date) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}

function endOfDay(d: Date) {
  const x = new Date(d);
  x.setHours(23, 59, 59, 999);
  return x;
}

function decToNumber(v: any) {
  return v === null || v === undefined ? 0 : Number(v.toString());
}

async function computeRevenue(transactions: any[]) {
  let income = 0;
  let refunds = 0;
  for (const t of transactions) {
    if (t.category === "income" && t.transactionType === "credit") income += decToNumber(t.amount);
    if (t.category === "refund") refunds += decToNumber(t.amount);
  }
  return { income, refunds, revenue: income - refunds };
}

export async function getSummaryData(args: {
  userId: string;
  period: "daily" | "weekly" | "monthly";
  date?: string; // for daily (YYYY-MM-DD)
}) {
  const now = new Date();
  const userId = args.userId;

  let start: Date;
  let end: Date;
  let label: string;

  if (args.period === "daily") {
    const d = args.date ? new Date(args.date + "T00:00:00") : now;
    start = startOfDay(d);
    end = endOfDay(d);
    label = `Daily Sales (${toISODate(d)})`;
  } else if (args.period === "weekly") {
    const d = new Date(now);
    d.setDate(now.getDate() - 6);
    start = startOfDay(d);
    end = endOfDay(now);
    label = `Weekly Sales (${toISODate(start)} to ${toISODate(now)})`;
  } else {
    const d = new Date(now.getFullYear(), now.getMonth(), 1);
    start = startOfDay(d);
    end = endOfDay(new Date(now.getFullYear(), now.getMonth() + 1, 0));
    label = `Monthly Performance (${toISODate(start).slice(0, 7)})`;
  }

  const [transactions, expenses] = await Promise.all([
    prisma.transaction.findMany({
      where: {
        userId,
        transactionTime: { gte: start, lte: end },
      },
      select: { amount: true, category: true, transactionType: true },
    }),
    prisma.expense.findMany({
      where: {
        userId,
        expenseTime: { gte: start, lte: end },
      },
      select: { amount: true },
    }),
  ]);

  const { income, refunds, revenue } = await computeRevenue(transactions);
  const expenseTotal = expenses.reduce((acc, e) => acc + decToNumber(e.amount), 0);
  const profit = revenue - expenseTotal;

  return {
    label,
    start,
    end,
    income,
    refunds,
    revenue,
    expenseTotal,
    profit,
  };
}

export function csvFromSummary(summary: Awaited<ReturnType<typeof getSummaryData>>) {
  const rows = [
    ["Metric", "Value"],
    ["Income (credits)", summary.income.toFixed(2)],
    ["Refunds (credited reversals)", summary.refunds.toFixed(2)],
    ["Revenue (income - refunds)", summary.revenue.toFixed(2)],
    ["Expenses", summary.expenseTotal.toFixed(2)],
    ["Estimated Profit", summary.profit.toFixed(2)],
  ];
  const escapeCell = (v: string) => {
    const s = String(v);
    if (s.includes(",") || s.includes('"') || s.includes("\n")) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  return rows.map((r) => r.map((c) => escapeCell(c)).join(",")).join("\n");
}

export async function pdfBufferFromSummary(summary: Awaited<ReturnType<typeof getSummaryData>>) {
  const doc = new PDFDocument({ margin: 40 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));

  doc.fontSize(18).text(summary.label, { align: "left" });
  doc.moveDown();
  doc.fontSize(12).text(`From: ${summary.start.toISOString().slice(0, 10)}  |  To: ${summary.end.toISOString().slice(0, 10)}`);
  doc.moveDown();

  const lines = [
    ["Income (credits)", `INR ${summary.income.toFixed(2)}`],
    ["Refunds", `INR ${summary.refunds.toFixed(2)}`],
    ["Revenue (income - refunds)", `INR ${summary.revenue.toFixed(2)}`],
    ["Expenses", `INR ${summary.expenseTotal.toFixed(2)}`],
    ["Estimated Profit", `INR ${summary.profit.toFixed(2)}`],
  ];

  for (const [k, v] of lines) {
    doc.fontSize(11).text(k);
    doc.fontSize(13).text(v, { indent: 10 });
    doc.moveDown(0.4);
  }

  doc.moveDown(1);
  doc.fontSize(9).fillColor("#666666").text("Generated by Small Business Smart Assistant (UPI++).");

  doc.end();

  await new Promise<void>((resolve) => doc.on("end", () => resolve()));
  return Buffer.concat(chunks);
}

